services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
    env_file:
      - .dockerenv
  db:
    # The database contains only cached public records, so no meaningful secrets here.
    image: mongo:latest
    hostname: hbp_webapp_mongodb
    environment:
      - DATABASE_NAME=hbp_webapp
      - WELL_RECORDS_COLLECTION=well_records
    ports:
      - "27017:27017"